/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as DiferenciaisRouteImport } from './routes/diferenciais'
import { Route as ContactosRouteImport } from './routes/contactos'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiferenciaisRoute = DiferenciaisRouteImport.update({
  id: '/diferenciais',
  path: '/diferenciais',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/contactos': typeof ContactosRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/contactos': typeof ContactosRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/contactos': typeof ContactosRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/contactos' | '/diferenciais' | '/servicos' | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/contactos' | '/diferenciais' | '/servicos' | '/sobre'
  id: '__root__' | '/contactos' | '/diferenciais' | '/servicos' | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ContactosRoute: typeof ContactosRoute
  DiferenciaisRoute: typeof DiferenciaisRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diferenciais': {
      id: '/diferenciais'
      path: '/diferenciais'
      fullPath: '/diferenciais'
      preLoaderRoute: typeof DiferenciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ContactosRoute: ContactosRoute,
  DiferenciaisRoute: DiferenciaisRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
